version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_URI=mongodb://mongo:27017/hospital_db
    depends_on:
      - mongo
      - ai-service

  ai-service:
    build:
      context: .
      dockerfile: docker/ai/Dockerfile
    volumes:
      - ./ai-models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
